name: CI - Python

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Rodar script
      run: python main.py

    - name: Notificar Microsoft Teams
      if: always()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
              "text": "🚀 Novo evento no GitHub!\nRepositório: ${{ github.repository }}\nBranch: ${{ github.ref }}\nStatus: ${{ job.status }}"
            }' \
        ${{ secrets.TEAMS_WEBHOOK_URL }}
      