name: CI - Python

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Rodar script
      run: python main.py

    - name: Notificar no Teams
      if: always()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "summary": "GitHub Actions",
          "themeColor": "0076D7",
          "title": "🚀 Pipeline executado!",
          "text": "Repositório: meu-projeto-devops2\nStatus: Concluído com sucesso ✅"
        }' \
        "https://default8a1ef6c383244103bf4a1328c5dc36.53.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/5ca2963e6bee4d50bb8a9ce7a3ecc18f/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=HWaAuLnatUfNyItKPn3VAsnMradpCnboFHdUCN3xHKk"
          