name: CI - Python

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install pytest

    - name: Rodar testes
      run: PYTHONPATH=. pytest

    - name: Notificar no Teams
      if: always()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "summary": "GitHub Actions",
          "themeColor": "0076D7",
          "title": "🚀 Pipeline executado!",
          "text": "Repositório: ${{ github.repository }}\nBranch: ${{ github.ref }}\nStatus: ${{ job.status }}"
        }' \
        ${{ secrets.TEAMS_WEBHOOK_URL }}